version = 1
enabled = true
behavior = "ipcidr"
output = "CN_IP_min"


[[sources]]
name = "gaoyifan China IPv4"
url = "https://raw.githubusercontent.com/gaoyifan/china-operator-ip/ip-lists/china.txt"
format = "text"
optional = true

[[sources]]
name = "gaoyifan China IPv6"
url = "https://raw.githubusercontent.com/gaoyifan/china-operator-ip/ip-lists/china6.txt"
format = "text"
optional = true



[[exclude]]
name = "No-CN ips"
path = "LocalRules/exclude/CNIP.txt"
format = "text"
optional = true
