from __future__ import annotations

import base64
import io
import struct
import unittest
from typing import Callable
from unittest.mock import patch

import zstandard

from scripts.jyrules.errors import BuildError
from scripts.jyrules.mrs import decode_domain_mrs


# Generated by Mihomo v1.19.30 from example.com, .example.com, and +.example.com.
EXACT_MRS = base64.b64decode(
    "KLUv/QQANQEAZAFNUlMBAAhqqqoAC21vYy5lbHBtYXhlBQBgmJ3yaLrBMgGu0wIITaSF"
)
DOT_MRS = base64.b64decode(
    "KLUv/QQATQEAlAFNUlMBACAGqqqqAA1tb2MuZWxwbWF4ZS4rBQBgoJ3naGbBMgGu0wKJA/qt"
)
PLUS_MRS = base64.b64decode(
    "KLUv/QQATQEAlAFNUlMBACgGqqqqAA1tb2MuZWxwbWF4ZS4rBQBgoJ3naGbBMgGu0wItMyBa"
)


def mutate_raw(data: bytes, mutation: Callable[[bytearray], None]) -> bytes:
    with zstandard.ZstdDecompressor().stream_reader(io.BytesIO(data)) as stream:
        raw = bytearray(stream.read())
    mutation(raw)
    return zstandard.ZstdCompressor().compress(raw)


class DomainMrsTests(unittest.TestCase):
    def test_distinguishes_exact_dot_and_plus_semantics(self) -> None:
        self.assertEqual(decode_domain_mrs(EXACT_MRS), ("example.com",))
        self.assertEqual(decode_domain_mrs(DOT_MRS), (".example.com",))
        self.assertEqual(decode_domain_mrs(PLUS_MRS), ("+.example.com",))

    def test_rejects_wrong_behavior_and_trailing_data(self) -> None:
        wrong_behavior = mutate_raw(EXACT_MRS, lambda raw: raw.__setitem__(4, 1))
        trailing = mutate_raw(EXACT_MRS, lambda raw: raw.extend(b"unexpected"))

        with self.assertRaisesRegex(BuildError, "behavior"):
            decode_domain_mrs(wrong_behavior)
        with self.assertRaisesRegex(BuildError, "trailing"):
            decode_domain_mrs(trailing)

    def test_rejects_out_of_range_leaf_and_broken_compression(self) -> None:
        def add_out_of_range_leaf(raw: bytearray) -> None:
            leaves_word = struct.unpack_from(">Q", raw, 30)[0]
            struct.pack_into(">Q", raw, 30, leaves_word | (1 << 63))

        malformed = mutate_raw(EXACT_MRS, add_out_of_range_leaf)
        with self.assertRaisesRegex(BuildError, "out-of-range"):
            decode_domain_mrs(malformed)
        with self.assertRaises(BuildError):
            decode_domain_mrs(EXACT_MRS[:10])

    def test_rejects_oversized_zero_bitmap_before_bit_scanning(self) -> None:
        def insert_extra_leaves_word(raw: bytearray) -> None:
            struct.pack_into(">q", raw, 22, 2)
            raw[38:38] = b"\x00" * 8

        malformed = mutate_raw(EXACT_MRS, insert_extra_leaves_word)
        with self.assertRaisesRegex(BuildError, "leaves bitmap.*invalid length"):
            decode_domain_mrs(malformed)

    def test_domain_tree_has_an_explicit_node_limit(self) -> None:
        with patch("scripts.jyrules.mrs.MAX_DOMAIN_NODES", 10):
            with self.assertRaisesRegex(BuildError, "trie-node limit"):
                decode_domain_mrs(PLUS_MRS)


if __name__ == "__main__":
    unittest.main()
